require "asset.scripts.enum.color"
require "asset.scripts.enum.ui_type"
require "asset.scripts.enum.enum_of_event"
require "asset.scripts.enum.hid_type"
require "asset.scripts.enum.moveable_type"
require "asset.scripts.enum.stage_enum"
