---@class (partial) App: Object
---@field CONTROLLER Controller 控制器
---@field SETTINGS Settings 设置
---@field window Window 窗口
---@field CANVAS Canvas
---@field ROOM {Node: Node, ORIG: {x: number, y: number, r: number}}   房间, 就是游戏的主场景, 一切节点的根节点
---@field jiggle number 震动, 用于屏幕震动, 如果是 0 则不震动, 需要震动的时候加一个值, 震动过程会逐渐减小到 0
---@field I NodeList
---@field under_overlay boolean 是否显示底层覆盖?????? 不知道是什么东西
---@field TILESCALE number 地图缩放比例
---@field TILESIZE number 地图单元格大小
---@field STAGE_OBJECT_INTERRUPT boolean 不知道具体作用是什么
---@field STAGE_OBJECTS Node[][] 场景中使用到的所有 Node , 当 STAGE 改变时, 可以通过这里删除所有 Node
---@field fbf boolean frame by frame 模式, 如果为 true, 则每帧都渲染, 否则每秒渲染 60 帧, 和 new_frame 配合使用
---@field new_frame boolean 是否是新的一帧, 如果为 true, 则渲染新的一帧, 否则渲染旧的一帧, 和 fbf 配合使用
---@field MOVEABLES Moveable[] 所有 Moveable 的列表, 包括 Moveable 的子类
---@field STAGE STAGES 当前场景
---@field STATE STATES 当前状态
---@field ROOM_PADDING_W number 房间左右边距, 以地图单元格为单位
---@field ROOM_PADDING_H number 房间上下边距, 以地图单元格为单位
---@field TILE_W number 地图单元格宽度, 以像素为单位
---@field TILE_H number 地图单元格高度, 以像素为单位
---@field PROFILES Profile[] 所有玩家的数据(最多三个玩家)


---@class Profile
---@field MEMORY {deck: string, stake: number} 记忆, 用于存储玩家的游戏数据
---@field stake number 当前赌注
---@field high_scores {hand: {label: string, amt: number}, furthest_round: {label: string, amt: number}, furthest_ante: {label: string, amt: number}, most_money: {label: string, amt: number}, boss_streak: {label: string, amt: number}, collection: {label: string, amt: number, tot: number}, win_streak: {label: string, amt: number}, current_streak: {label: string, amt: number}, poker_hand: {label: string, amt: number}} 最高得分
---@field career_stats {c_round_interest_cap_streak: number, c_dollars_earned: number, c_shop_dollars_spent: number, c_tarots_bought: number, c_planets_bought: number, c_playing_cards_bought: number, c_vouchers_bought: number, c_tarot_reading_used: number, c_planetarium_used: number, c_shop_rerolls: number, c_cards_played: number, c_cards_discarded: number, c_losses: number, c_wins: number, c_rounds: number, c_hands_played: number, c_face_cards_played: number, c_jokers_sold: number, c_cards_sold: number, c_single_hand_round_streak: number} 职业统计
---@field progress {joker_stickers: {tally: number, of: number}, deck_stakes: {tally: number, of: number}, challenges: {tally: number, of: number}} 进度
---@field joker_usage {tally: number, of: number} 使用次数
---@field consumeable_usage {tally: number, of: number} 消耗品使用次数
---@field voucher_usage {tally: number, of: number} 优惠券使用次数
---@field hand_usage {tally: number, of: number} 手牌使用次数
---@field deck_usage {tally: number, of: number} 牌组使用次数
---@field deck_stakes {tally: number, of: number} 牌组赌注
---@field challenges_unlocked nil 挑战解锁
---@field challenge_progress {completed: {label: string, amt: number}[], unlocked: {label: string, amt: number}[]} 挑战进度
