---@class (partial) App
---@field METRICS Metrics 玩家成就记录
---@field CONTROLLER Controller 控制器
---@field SETTINGS Settings 设置
---@field TIMERS Timer 计时器
---@field window Window 窗口
---@field CANVAS Canvas
---@field CANV_SCALE number 画布缩放比例
---@field AA_CANVAS? Canvas 抗锯齿画布?
---@field ROOM Node 房间, 就是游戏的主场景, 一切节点的根节点
---@field ROOM_ATTACH Moveable
---@field jiggle number 震动, 用于屏幕震动, 如果是 0 则不震动, 需要震动的时候加一个值, 震动过程会逐渐减小到 0
---@field I NodeList
---@field under_overlay boolean 是否显示底层覆盖?????? 不知道是什么东西
---@field OVERLAY_MENU? UIBox 菜单
---@field OVERLAY_TUTORIAL? UIBox 教程
---@field achievement_notification? UIBox 成就通知
---@field online_leaderboard? UIBox 在线排行榜
---@field debug_tools? UIBox 调试工具
---@field screenwipe? UIBox 屏幕擦除
---@field TILESCALE number 地图缩放比例
---@field TILESIZE number 地图单元格大小
---@field STAGE_OBJECT_INTERRUPT boolean 不知道具体作用是什么
---@field STAGE_OBJECTS Node[][] 场景中使用到的所有 Node , 当 STAGE 改变时, 可以通过这里删除所有 Node
---@field fbf boolean frame by frame 模式, 如果为 true, 则每帧都渲染, 否则每秒渲染 60 帧, 和 new_frame 配合使用
---@field new_frame boolean 是否是新的一帧, 如果为 true, 则渲染新的一帧, 否则渲染旧的一帧, 和 fbf 配合使用
---@field MOVEABLES Moveable[] 所有 Moveable 的列表, 包括 Moveable 的子类
---@field STAGE STAGES 当前场景
---@field STATE STATES 当前状态
---@field PROFILES Profile 所有玩家的数据(最多三个玩家)
---@field SOUND_MANAGER SoundManager 声音管理器
---@field SAVE_MANAGER SaveManager 存档管理器
---@field HTTP_MANAGER HttpManager 网络管理器
---@field SHADERS table<string, Shader> 所有着色器
---@field LANG LanguageConfigItem 当前使用的语言对象
---@field Tile Tile 地图单元格
---@field Features FeatureConfig 特性配置
---@field E_MANAGER EventManager 事件管理器
---@field real_dt number 真实的 dt
---@field ARGS any 记录一些参数, 之后要解耦出来
---@field SPLASH_BACK Sprite 启动画面背景
---@field SPLASH_FRONT Sprite 启动画面前景
---@field SPLASH_LOGO Sprite 启动画面 logo
---@field debug_background_toggle boolean 是否显示调试背景
---@field debug_UI_toggle boolean 是否显示调试 UI
---@field debug_splash_size_toggle boolean 是否显示调试启动画面大小
---@field recording_mode boolean 是否是录制模式
---@field video_control boolean 是否是视频控制模式
---@field screenglitch boolean 是否开启屏幕故障 shader 使用
---@field ACC_state STATES 加速参数的判断状态, 当状态改变时, 加速参数清零, 其实就是上一帧的状态
---@field ACC number 加速参数
---@field SPEEDFACTOR number 速度因子


---@alias NodeList {
---NODE: Node[],
---MOVEABLE: Moveable[],
---UIBOX: UIBox[],
---SPRITE: Sprite[],
---CARD: Card[],
---CARDAREA: CardArea[],
---POPUP: Node[],
---ALERT: Node[],
---}
