---@meta

---@class (partial) Moveable: Node
---field T Transform 变换 {x, y, w, h, r, scale} (逻辑坐标), 显式声明避免 glue_to_major 中 self.T = major_tab.T 的循环推断
---@field velocity Velocity 速度
---@field shadow_parrallax Vec2 阴影的偏移, 受主场景就是 ROOM 影响
---@field role MoveableRole 在 Moveable 中初始化
---@field alignment Alignment
---@field pinch { x: boolean, y: boolean } 快速完成过渡
---@field last_moved number 上次移动时间
---@field last_aligned number 上次对齐时间
---@field static_rotation boolean 是否静态旋转?
---@field offset Vec2 偏移
---@field Mid Moveable 在水平和垂直居中对齐时, 参考的中心点, 就是以哪个 Node 当作中心点, 一般默认为自己,
---@field shadow_height number 阴影高度??
---@field VT Transform 缓动变换成使用, 引擎会自动计算到 T
---@field layered_parallax Vec2 分层偏移????
---@field parent Moveable 父节点

---@class AlignmentArgs
---@field major Moveable
---@field bond? BondType
---@field xy_bond? BondType
---@field wh_bond? BondType
---@field r_bond? BondType
---@field scale_bond? BondType
---@field offset? Vec2
---@field type? AlignmentType
---@field lr_clamp? boolean
