---@meta

---@class ParticlesConfig
---@field fill? boolean
---@field padding? number
---@field attach? Moveable 要附着到哪个 Moveable 上
---@field timer? number
---@field timer_type? fun(): number
---@field lifespan? number
---@field speed? number
---@field max? number
---@field pulse_max? number
---@field vel_variation? number
---@field scale? number
---@field colours? Color[]
---@field initialize? boolean
