---@meta

---@class (partial) Particles: Moveable 粒子发射器
---@field particles Particle[] 粒子
---@field private scale number 粒子的参数缩放, 不是 Transform 的缩放
---@field private lifespan number 产生的粒子的寿命

---@class ParticlesConfig
---@field fill? boolean
---@field padding? number
---@field attach? Moveable 要附着到哪个 Moveable 上
---@field timer? number
---@field timer_type? fun(): number
---@field lifespan? number
---@field speed? number
---@field max? number
---@field pulse_max? number
---@field vel_variation? number
---@field scale? number
---@field colours? Color[]
---@field initialize? boolean
