---@class (partial) Sprite: Moveable
---@field atlas AtlasConfigItem
---@field draw_steps DrawStep[]
---@field scale Vec2 这个 scale 居然不是缩放, 是图集中每个元素的大小

---@class DataSendToShader
---@field name string
---@field val? any
---@field func? function
---@field ref_table? table
---@field ref_value?string

---@class DrawStep
---@field shader string
---@field send? DataSendToShader[]
---@field shadow_height? number
---@field ms? number
---@field mr? number
---@field mx? number
---@field my? number
---@field no_tilt? boolean
---@field other_obj? Sprite 在概率是一个 Sprite
