---@class UIConfig: Object
---@field object  any
---@field text?   string
---@field scale?  number
---@field colour? Color
---@field align?  string
---@field offset? { x: number, y: number }
---@field major?  Node
---@field bond?   string
---@field button_dist? number 按钮距离
---@field button_UIE UIElement
---@field shadow_colour? Color
---@field vert boolean
---@field r boolean 这到底是什么意思?
---@field button_delay number 按钮延迟?
---@field hover boolean 是否悬停?
---@field emboss number 凹凸程度?
---@field button_delay_progress number 按钮延迟进度?
---@field progress_bar? table 进度条?
---@field focus_with_object boolean 是否聚焦于对象?