---@class UIConfig: Object
---@field object  any
---@field text?   string
---@field scale?  number
---@field colour? Color
---@field align?  string
---@field offset? { x: number, y: number }
---@field major?  Node
---@field bond?   string
---@field button_dist? number 按钮距离
---@field button_UIE UIElement
---@field shadow_colour? Color
---@field vert boolean
---@field r boolean 这到底是什么意思?
